version: '3.8'
services:
  parser:
    image: node:15.6.0-alpine
    command: >
      /bin/sh -c "
      cd /app
      && npm install --production
      && node index.js"
    volumes:
      - .:/app
    env_file: .env

networks:
  default:
    external: true
    name: ufop
